# Branch name patterns to automatically label PRs
enhancement:
- feature/*
- feat/*
- enhancement/*
- improve/*
- improvement/*
bug:
- fix/*
chore:
- chore/*
documentation:
- docs/*
- documentation/*
# Auto dependency update branches from Dependabot or Renovate
dependencies:
- dependabot/**
- renovate/**
- pre-commit-ci-update-config
