name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
exclude-contributors:
- dependabot
- dependabot[bot]
- pre-commit-ci
- pre-commit-ci[bot]
- '@pre-commit-ci[bot]'
- Renovate Bot
- renovate[bot]
- GitHub Action
categories:
- title: 🚀 Features
  label: feature
- title: 🐛 Bug Fixes
  labels:
  - fix
  - bugfix
  - bug
- title: 🧰 Maintenance
  labels:
  - chore
  - maintenance
- title: 📚 Documentation
  labels:
  - documentation
  - docs
- title: ⬆️ Dependencies
  labels:
  - dependencies
  - python
  - github-actions
  - pre-commit
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: \<*_&   # You can add # and @ to disable mentions and add ` to disable code blocks.
version-resolver:
  major:
    labels:
    - major
    - breaking
  minor:
    labels:
    - minor
    - feature
    - enhancement
  patch:
    labels:
    - patch
    - fix
    - bugfix
    - bug
    - maintenance
    - docs
    - dependencies
    - security
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
