image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- Static Code Analysis
- deploy

cache:
  paths:
  - .cache/pip
  - venv/

before_script:
- python -V    # Print out python version for debugging
- python -m pip poetry
- poetry install

Black Linter:
  when: always
  stage: Static Code Analysis
  tags:
  - pi
  before_script:
  - python -V
  - pip install black
  script:
  - pip install black
  - black  --check --diff ./
  allow_failure: true

Flake Linter:
  when: always
  stage: Static Code Analysis
  tags:
  - pi
  script:
  - poetry run flake8 --statistics
  allow_failure: true

pyinstall:
  when: manual
  stage: deploy
  image: tobix/pywine:3.10
  retry: 2
  tags:
  - win-docker
  before_script:
  - . /opt/mkuserwineprefix
  - wine /opt/wineprefix/drive_c/Python39/Python.exe -v
  - wine /opt/wineprefix/drive_c/Python39/Python.exe -m pip -r requirements.txt
  script:
  - wine /opt/wineprefix/drive_c/Python39/Scripts/pyinstaller.exe auto_print.spec
  artifacts:
    paths:
    - dist/*
  # rules:
  # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
