name: Python Test Pipline

on:
- push
- pull_request

jobs:
  test-jub:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip      # caching pip dependencies
    - run: pip install poetry
