name: checks
on:
- push
- pull_request

env:
  GOPROXY: https://goproxy.io,direct
  GOPATH: /go_path
  GOCACHE: /go_cache

jobs:
  lint:
    name: check and test
    runs-on: pi
    steps:
    - name: cache go path
      id: cache-go-path
      uses: https://github.com/actions/cache@v3
      with:
        path: /go_path
        key: go_path-${{ github.repository }}-${{ github.ref_name }}
        restore-keys: |
          go_path-${{ github.repository }}-
          go_path-
    - name: cache go cache
      id: cache-go-cache
      uses: https://github.com/actions/cache@v3
      with:
        path: /go_cache
        key: go_cache-${{ github.repository }}-${{ github.ref_name }}
        restore-keys: |
          go_cache-${{ github.repository }}-
          go_cache-
    - uses: workflows/setup-go@v3
      with:
        go-version: 1.20
    - uses: workflows/checkout@v3
    - name: vet checks
      run: go vet -v ./...
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./pkg/jobparser
        # TODO test more packages
