name: workflow test
on: push

jobs:
  test:
    name: Test
    runs-on: pi

    steps:
    - name: Test with inputs
      run: |
        echo "Hello ${{ github.event.inputs.NAME }} and ${{ github.event.inputs.SOME_VALUE }}!"
