name: CI

on:
  push:
  release:
    types: [published]

jobs:

  test:
    name: Test
    runs-on: windows-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        pipx install poetry
        poetry install --only main,test
    - name: Run tests
      run: |
        poetry run pytest -v

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        pipx install poetry
        poetry install --only main,docs
    - name: Build English documentation
      run: |
        cd docs
        poetry run make html
#    - name: Build German documentation
#      run: |
#        cd docs
#        poetry run make gettext
#        # Remove locale directory if it exists to prevent FileExistsError
#        rm -rf locale
#        poetry run sphinx-intl update -p _build/gettext -l de
#        poetry run make -e SPHINXOPTS="-D language='de'" html
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: |
          docs/_build/html
          docs/_build/de/html

  wheel-build:
    name: Wheel Build
    needs: [test, docs]
    runs-on: windows-latest
    # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        pipx install poetry
    - name: wheel-build
      run: |
        poetry build
    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: distribution-packages
        path: |
          dist/*.whl

  msi-build:
    name: MSI-Build
    needs: [test, docs]
    runs-on: windows-latest
    # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        pipx install poetry

    - name: MSI-build
      run: |
        poetry install --only main,build
        poetry run msi_setup.py bdist_msi
    - name: Upload MSI artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSI
        path: |
          dist/*.msi

  deploy-docs:
    name: Deploy Documentation
    needs: [docs]
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Download documentation artifact
      uses: actions/download-artifact@v4
      with:
        name: documentation
        path: documentation
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation
