name: dependabot validate
on:
  push:
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: marocchino/validate-dependabot@v3
      id: validate
    - uses: marocchino/sticky-pull-request-comment@v2
      if: always()
      with:
        header: validate-dependabot
        message: ${{ steps.validate.outputs.markdown }}
