name: Release Drafter

on:
  push:
    branches:
    - main
    - draft-release
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == true || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Draft Release
      uses: release-drafter/release-drafter@v6
      with:
        config-name: .github/release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
